version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.3.1
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}